import sqlite3

import psycopg

from cloud.config import (
    DATABASE_ENGINE,
    POSTGRES_DATABASE,
    POSTGRES_HOST,
    POSTGRES_PASSWORD,
    POSTGRES_PORT,
    POSTGRES_USER,
    SQLITE_DATABASE_PATH,
)


def conectar():
    """Abre uma conexao com o banco configurado para a Cloud."""
    if DATABASE_ENGINE == "sqlite":
        return sqlite3.connect(SQLITE_DATABASE_PATH)

    if DATABASE_ENGINE == "postgres":
        return psycopg.connect(
            host=POSTGRES_HOST,
            port=POSTGRES_PORT,
            dbname=POSTGRES_DATABASE,
            user=POSTGRES_USER,
            password=POSTGRES_PASSWORD,
        )

    raise ValueError(
        f"Mecanismo de banco nao suportado: {DATABASE_ENGINE}"
    )


def inicializar_banco():
    """Cria as tabelas iniciais da Cloud."""
    if DATABASE_ENGINE == "sqlite":
        inicializar_banco_sqlite()
        return

    if DATABASE_ENGINE == "postgres":
        inicializar_banco_postgres()
        return

    raise ValueError(
        f"Mecanismo de banco nao suportado: {DATABASE_ENGINE}"
    )


def inicializar_banco_sqlite():
    conexao = conectar()
    cursor = conexao.cursor()

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS companies (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            company_id TEXT NOT NULL UNIQUE,
            company_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS terminals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            terminal_id TEXT NOT NULL UNIQUE,
            company_id TEXT NOT NULL,
            terminal_name TEXT NOT NULL,
            product TEXT NOT NULL,
            version TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (company_id) REFERENCES companies(company_id)
        )
        """
    )

    conexao.commit()
    conexao.close()


def inicializar_banco_postgres():
    conexao = conectar()
    cursor = conexao.cursor()

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS companies (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id TEXT NOT NULL UNIQUE,
            company_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS terminals (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            terminal_id TEXT NOT NULL UNIQUE,
            company_id TEXT NOT NULL,
            terminal_name TEXT NOT NULL,
            product TEXT NOT NULL,
            version TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (company_id) REFERENCES companies(company_id)
        )
        """
    )

    conexao.commit()
    conexao.close()


def registrar_terminal(
    company_id,
    company_name,
    terminal_id,
    terminal_name,
    product,
    version,
):
    """Cadastra a empresa e registra ou atualiza o terminal."""
    conexao = conectar()
    cursor = conexao.cursor()

    if DATABASE_ENGINE == "sqlite":
        placeholder = "?"
    elif DATABASE_ENGINE == "postgres":
        placeholder = "%s"
    else:
        conexao.close()
        raise ValueError(
            f"Mecanismo de banco nao suportado: {DATABASE_ENGINE}"
        )

    cursor.execute(
        f"""
        INSERT INTO companies (company_id, company_name)
        VALUES ({placeholder}, {placeholder})
        ON CONFLICT(company_id) DO UPDATE SET
            company_name = excluded.company_name
        """,
        (company_id, company_name),
    )

    cursor.execute(
        f"""
        INSERT INTO terminals (
            terminal_id,
            company_id,
            terminal_name,
            product,
            version
        )
        VALUES (
            {placeholder},
            {placeholder},
            {placeholder},
            {placeholder},
            {placeholder}
        )
        ON CONFLICT(terminal_id) DO UPDATE SET
            company_id = excluded.company_id,
            terminal_name = excluded.terminal_name,
            product = excluded.product,
            version = excluded.version,
            updated_at = CURRENT_TIMESTAMP
        """,
        (
            terminal_id,
            company_id,
            terminal_name,
            product,
            version,
        ),
    )

    conexao.commit()
    conexao.close()


def listar_empresas():
    """Lista as empresas cadastradas na Lancaster Cloud."""
    conexao = conectar()
    cursor = conexao.cursor()

    cursor.execute(
        """
        SELECT
            company_id,
            company_name,
            status,
            created_at
        FROM companies
        ORDER BY company_name
        """
    )

    empresas = cursor.fetchall()
    conexao.close()

    return empresas

def cadastrar_empresa(company_id, company_name):
    """Cadastra uma nova empresa na Lancaster Cloud."""
    conexao = conectar()
    cursor = conexao.cursor()

    if DATABASE_ENGINE == "sqlite":
        placeholder = "?"
    elif DATABASE_ENGINE == "postgres":
        placeholder = "%s"
    else:
        conexao.close()
        raise ValueError(
            f"Mecanismo de banco nao suportado: {DATABASE_ENGINE}"
        )

    cursor.execute(
        f"""
        INSERT INTO companies (
            company_id,
            company_name
        )
        VALUES (
            {placeholder},
            {placeholder}
        )
        """,
        (
            company_id,
            company_name,
        ),
    )

    conexao.commit()
    conexao.close()

def buscar_empresa(company_id):
    """Busca uma empresa pelo company_id."""
    conexao = conectar()
    cursor = conexao.cursor()

    if DATABASE_ENGINE == "sqlite":
        placeholder = "?"
    elif DATABASE_ENGINE == "postgres":
        placeholder = "%s"
    else:
        conexao.close()
        raise ValueError(
            f"Mecanismo de banco nao suportado: {DATABASE_ENGINE}"
        )

    cursor.execute(
        f"""
        SELECT
            company_id,
            company_name,
            status,
            created_at
        FROM companies
        WHERE company_id = {placeholder}
        """,
        (company_id,),
    )

    empresa = cursor.fetchone()
    conexao.close()

    return empresa

def buscar_terminal(terminal_id):
    """Busca um terminal pelo terminal_id."""
    conexao = conectar()
    cursor = conexao.cursor()

    if DATABASE_ENGINE == "sqlite":
        placeholder = "?"
    elif DATABASE_ENGINE == "postgres":
        placeholder = "%s"
    else:
        conexao.close()
        raise ValueError(
            f"Mecanismo de banco nao suportado: {DATABASE_ENGINE}"
        )

    cursor.execute(
        f"""
        SELECT
            terminal_id,
            company_id,
            terminal_name,
            product,
            version,
            created_at,
            updated_at
        FROM terminals
        WHERE terminal_id = {placeholder}
        """,
        (terminal_id,),
    )

    terminal = cursor.fetchone()
    conexao.close()

    return terminal